/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ManyTracks type.
 */
public class ManyTracks {
    private List<TrackObject> tracks;

    /**
     * Default constructor.
     */
    public ManyTracks() {
    }

    /**
     * Initialization constructor.
     * @param  tracks  List of TrackObject value for tracks.
     */
    public ManyTracks(
            List<TrackObject> tracks) {
        this.tracks = tracks;
    }

    /**
     * Getter for Tracks.
     * @return Returns the List of TrackObject
     */
    @JsonGetter("tracks")
    public List<TrackObject> getTracks() {
        return tracks;
    }

    /**
     * Setter for Tracks.
     * @param tracks Value for List of TrackObject
     */
    @JsonSetter("tracks")
    public void setTracks(List<TrackObject> tracks) {
        this.tracks = tracks;
    }

    /**
     * Converts this ManyTracks into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyTracks [" + "tracks=" + tracks + "]";
    }

    /**
     * Builds a new {@link ManyTracks.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyTracks.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(tracks);
        return builder;
    }

    /**
     * Class to build instances of {@link ManyTracks}.
     */
    public static class Builder {
        private List<TrackObject> tracks;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  tracks  List of TrackObject value for tracks.
         */
        public Builder(List<TrackObject> tracks) {
            this.tracks = tracks;
        }

        /**
         * Setter for tracks.
         * @param  tracks  List of TrackObject value for tracks.
         * @return Builder
         */
        public Builder tracks(List<TrackObject> tracks) {
            this.tracks = tracks;
            return this;
        }

        /**
         * Builds a new {@link ManyTracks} object using the set fields.
         * @return {@link ManyTracks}
         */
        public ManyTracks build() {
            return new ManyTracks(tracks);
        }
    }
}
