/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ManyGenres type.
 */
public class ManyGenres {
    private List<String> genres;

    /**
     * Default constructor.
     */
    public ManyGenres() {
    }

    /**
     * Initialization constructor.
     * @param  genres  List of String value for genres.
     */
    public ManyGenres(
            List<String> genres) {
        this.genres = genres;
    }

    /**
     * Getter for Genres.
     * @return Returns the List of String
     */
    @JsonGetter("genres")
    public List<String> getGenres() {
        return genres;
    }

    /**
     * Setter for Genres.
     * @param genres Value for List of String
     */
    @JsonSetter("genres")
    public void setGenres(List<String> genres) {
        this.genres = genres;
    }

    /**
     * Converts this ManyGenres into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyGenres [" + "genres=" + genres + "]";
    }

    /**
     * Builds a new {@link ManyGenres.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyGenres.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(genres);
        return builder;
    }

    /**
     * Class to build instances of {@link ManyGenres}.
     */
    public static class Builder {
        private List<String> genres;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  genres  List of String value for genres.
         */
        public Builder(List<String> genres) {
            this.genres = genres;
        }

        /**
         * Setter for genres.
         * @param  genres  List of String value for genres.
         * @return Builder
         */
        public Builder genres(List<String> genres) {
            this.genres = genres;
            return this;
        }

        /**
         * Builds a new {@link ManyGenres} object using the set fields.
         * @return {@link ManyGenres}
         */
        public ManyGenres build() {
            return new ManyGenres(genres);
        }
    }
}
