/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ManyDevices type.
 */
public class ManyDevices {
    private List<DeviceObject> devices;

    /**
     * Default constructor.
     */
    public ManyDevices() {
    }

    /**
     * Initialization constructor.
     * @param  devices  List of DeviceObject value for devices.
     */
    public ManyDevices(
            List<DeviceObject> devices) {
        this.devices = devices;
    }

    /**
     * Getter for Devices.
     * @return Returns the List of DeviceObject
     */
    @JsonGetter("devices")
    public List<DeviceObject> getDevices() {
        return devices;
    }

    /**
     * Setter for Devices.
     * @param devices Value for List of DeviceObject
     */
    @JsonSetter("devices")
    public void setDevices(List<DeviceObject> devices) {
        this.devices = devices;
    }

    /**
     * Converts this ManyDevices into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyDevices [" + "devices=" + devices + "]";
    }

    /**
     * Builds a new {@link ManyDevices.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyDevices.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(devices);
        return builder;
    }

    /**
     * Class to build instances of {@link ManyDevices}.
     */
    public static class Builder {
        private List<DeviceObject> devices;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  devices  List of DeviceObject value for devices.
         */
        public Builder(List<DeviceObject> devices) {
            this.devices = devices;
        }

        /**
         * Setter for devices.
         * @param  devices  List of DeviceObject value for devices.
         * @return Builder
         */
        public Builder devices(List<DeviceObject> devices) {
            this.devices = devices;
            return this;
        }

        /**
         * Builds a new {@link ManyDevices} object using the set fields.
         * @return {@link ManyDevices}
         */
        public ManyDevices build() {
            return new ManyDevices(devices);
        }
    }
}
