/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ManyEpisodes type.
 */
public class ManyEpisodes {
    private List<EpisodeObject> episodes;

    /**
     * Default constructor.
     */
    public ManyEpisodes() {
    }

    /**
     * Initialization constructor.
     * @param  episodes  List of EpisodeObject value for episodes.
     */
    public ManyEpisodes(
            List<EpisodeObject> episodes) {
        this.episodes = episodes;
    }

    /**
     * Getter for Episodes.
     * @return Returns the List of EpisodeObject
     */
    @JsonGetter("episodes")
    public List<EpisodeObject> getEpisodes() {
        return episodes;
    }

    /**
     * Setter for Episodes.
     * @param episodes Value for List of EpisodeObject
     */
    @JsonSetter("episodes")
    public void setEpisodes(List<EpisodeObject> episodes) {
        this.episodes = episodes;
    }

    /**
     * Converts this ManyEpisodes into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyEpisodes [" + "episodes=" + episodes + "]";
    }

    /**
     * Builds a new {@link ManyEpisodes.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyEpisodes.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(episodes);
        return builder;
    }

    /**
     * Class to build instances of {@link ManyEpisodes}.
     */
    public static class Builder {
        private List<EpisodeObject> episodes;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  episodes  List of EpisodeObject value for episodes.
         */
        public Builder(List<EpisodeObject> episodes) {
            this.episodes = episodes;
        }

        /**
         * Setter for episodes.
         * @param  episodes  List of EpisodeObject value for episodes.
         * @return Builder
         */
        public Builder episodes(List<EpisodeObject> episodes) {
            this.episodes = episodes;
            return this;
        }

        /**
         * Builds a new {@link ManyEpisodes} object using the set fields.
         * @return {@link ManyEpisodes}
         */
        public ManyEpisodes build() {
            return new ManyEpisodes(episodes);
        }
    }
}
