/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ManyAlbums type.
 */
public class ManyAlbums {
    private List<AlbumObject> albums;

    /**
     * Default constructor.
     */
    public ManyAlbums() {
    }

    /**
     * Initialization constructor.
     * @param  albums  List of AlbumObject value for albums.
     */
    public ManyAlbums(
            List<AlbumObject> albums) {
        this.albums = albums;
    }

    /**
     * Getter for Albums.
     * @return Returns the List of AlbumObject
     */
    @JsonGetter("albums")
    public List<AlbumObject> getAlbums() {
        return albums;
    }

    /**
     * Setter for Albums.
     * @param albums Value for List of AlbumObject
     */
    @JsonSetter("albums")
    public void setAlbums(List<AlbumObject> albums) {
        this.albums = albums;
    }

    /**
     * Converts this ManyAlbums into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyAlbums [" + "albums=" + albums + "]";
    }

    /**
     * Builds a new {@link ManyAlbums.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyAlbums.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(albums);
        return builder;
    }

    /**
     * Class to build instances of {@link ManyAlbums}.
     */
    public static class Builder {
        private List<AlbumObject> albums;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  albums  List of AlbumObject value for albums.
         */
        public Builder(List<AlbumObject> albums) {
            this.albums = albums;
        }

        /**
         * Setter for albums.
         * @param  albums  List of AlbumObject value for albums.
         * @return Builder
         */
        public Builder albums(List<AlbumObject> albums) {
            this.albums = albums;
            return this;
        }

        /**
         * Builds a new {@link ManyAlbums} object using the set fields.
         * @return {@link ManyAlbums}
         */
        public ManyAlbums build() {
            return new ManyAlbums(albums);
        }
    }
}
