/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for MeTracksRequest type.
 */
public class MeTracksRequest {
    private List<String> ids;

    /**
     * Default constructor.
     */
    public MeTracksRequest() {
    }

    /**
     * Initialization constructor.
     * @param  ids  List of String value for ids.
     */
    public MeTracksRequest(
            List<String> ids) {
        this.ids = ids;
    }

    /**
     * Getter for Ids.
     * A JSON array of the [Spotify IDs](/documentation/web-api/concepts/spotify-uris-ids). For
     * example: `["4iV5W9uYEdYUVa79Axb7Rh", "1301WleyT98MSxVHPZCA6M"]`&lt;br/&gt;A maximum of 50 items can
     * be specified in one request. _**Note**: if the `ids` parameter is present in the query
     * string, any IDs listed here in the body will be ignored._
     * @return Returns the List of String
     */
    @JsonGetter("ids")
    public List<String> getIds() {
        return ids;
    }

    /**
     * Setter for Ids.
     * A JSON array of the [Spotify IDs](/documentation/web-api/concepts/spotify-uris-ids). For
     * example: `["4iV5W9uYEdYUVa79Axb7Rh", "1301WleyT98MSxVHPZCA6M"]`&lt;br/&gt;A maximum of 50 items can
     * be specified in one request. _**Note**: if the `ids` parameter is present in the query
     * string, any IDs listed here in the body will be ignored._
     * @param ids Value for List of String
     */
    @JsonSetter("ids")
    public void setIds(List<String> ids) {
        this.ids = ids;
    }

    /**
     * Converts this MeTracksRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MeTracksRequest [" + "ids=" + ids + "]";
    }

    /**
     * Builds a new {@link MeTracksRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MeTracksRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(ids);
        return builder;
    }

    /**
     * Class to build instances of {@link MeTracksRequest}.
     */
    public static class Builder {
        private List<String> ids;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  ids  List of String value for ids.
         */
        public Builder(List<String> ids) {
            this.ids = ids;
        }

        /**
         * Setter for ids.
         * @param  ids  List of String value for ids.
         * @return Builder
         */
        public Builder ids(List<String> ids) {
            this.ids = ids;
            return this;
        }

        /**
         * Builds a new {@link MeTracksRequest} object using the set fields.
         * @return {@link MeTracksRequest}
         */
        public MeTracksRequest build() {
            return new MeTracksRequest(ids);
        }
    }
}
