/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PagedAlbums type.
 */
public class PagedAlbums {
    private PagingSimplifiedAlbumObject albums;

    /**
     * Default constructor.
     */
    public PagedAlbums() {
    }

    /**
     * Initialization constructor.
     * @param  albums  PagingSimplifiedAlbumObject value for albums.
     */
    public PagedAlbums(
            PagingSimplifiedAlbumObject albums) {
        this.albums = albums;
    }

    /**
     * Getter for Albums.
     * @return Returns the PagingSimplifiedAlbumObject
     */
    @JsonGetter("albums")
    public PagingSimplifiedAlbumObject getAlbums() {
        return albums;
    }

    /**
     * Setter for Albums.
     * @param albums Value for PagingSimplifiedAlbumObject
     */
    @JsonSetter("albums")
    public void setAlbums(PagingSimplifiedAlbumObject albums) {
        this.albums = albums;
    }

    /**
     * Converts this PagedAlbums into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PagedAlbums [" + "albums=" + albums + "]";
    }

    /**
     * Builds a new {@link PagedAlbums.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PagedAlbums.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(albums);
        return builder;
    }

    /**
     * Class to build instances of {@link PagedAlbums}.
     */
    public static class Builder {
        private PagingSimplifiedAlbumObject albums;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  albums  PagingSimplifiedAlbumObject value for albums.
         */
        public Builder(PagingSimplifiedAlbumObject albums) {
            this.albums = albums;
        }

        /**
         * Setter for albums.
         * @param  albums  PagingSimplifiedAlbumObject value for albums.
         * @return Builder
         */
        public Builder albums(PagingSimplifiedAlbumObject albums) {
            this.albums = albums;
            return this;
        }

        /**
         * Builds a new {@link PagedAlbums} object using the set fields.
         * @return {@link PagedAlbums}
         */
        public PagedAlbums build() {
            return new PagedAlbums(albums);
        }
    }
}
