/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PlaylistTracksRefObject type.
 */
public class PlaylistTracksRefObject {
    private String href;
    private Integer total;

    /**
     * Default constructor.
     */
    public PlaylistTracksRefObject() {
    }

    /**
     * Initialization constructor.
     * @param  href  String value for href.
     * @param  total  Integer value for total.
     */
    public PlaylistTracksRefObject(
            String href,
            Integer total) {
        this.href = href;
        this.total = total;
    }

    /**
     * Getter for Href.
     * A link to the Web API endpoint where full details of the playlist's tracks can be retrieved.
     * @return Returns the String
     */
    @JsonGetter("href")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHref() {
        return href;
    }

    /**
     * Setter for Href.
     * A link to the Web API endpoint where full details of the playlist's tracks can be retrieved.
     * @param href Value for String
     */
    @JsonSetter("href")
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * Getter for Total.
     * Number of tracks in the playlist.
     * @return Returns the Integer
     */
    @JsonGetter("total")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTotal() {
        return total;
    }

    /**
     * Setter for Total.
     * Number of tracks in the playlist.
     * @param total Value for Integer
     */
    @JsonSetter("total")
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * Converts this PlaylistTracksRefObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaylistTracksRefObject [" + "href=" + href + ", total=" + total + "]";
    }

    /**
     * Builds a new {@link PlaylistTracksRefObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaylistTracksRefObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .href(getHref())
                .total(getTotal());
        return builder;
    }

    /**
     * Class to build instances of {@link PlaylistTracksRefObject}.
     */
    public static class Builder {
        private String href;
        private Integer total;



        /**
         * Setter for href.
         * @param  href  String value for href.
         * @return Builder
         */
        public Builder href(String href) {
            this.href = href;
            return this;
        }

        /**
         * Setter for total.
         * @param  total  Integer value for total.
         * @return Builder
         */
        public Builder total(Integer total) {
            this.total = total;
            return this;
        }

        /**
         * Builds a new {@link PlaylistTracksRefObject} object using the set fields.
         * @return {@link PlaylistTracksRefObject}
         */
        public PlaylistTracksRefObject build() {
            return new PlaylistTracksRefObject(href, total);
        }
    }
}
