/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PlaylistSnapshotId type.
 */
public class PlaylistSnapshotId {
    private String snapshotId;

    /**
     * Default constructor.
     */
    public PlaylistSnapshotId() {
    }

    /**
     * Initialization constructor.
     * @param  snapshotId  String value for snapshotId.
     */
    public PlaylistSnapshotId(
            String snapshotId) {
        this.snapshotId = snapshotId;
    }

    /**
     * Getter for SnapshotId.
     * @return Returns the String
     */
    @JsonGetter("snapshot_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSnapshotId() {
        return snapshotId;
    }

    /**
     * Setter for SnapshotId.
     * @param snapshotId Value for String
     */
    @JsonSetter("snapshot_id")
    public void setSnapshotId(String snapshotId) {
        this.snapshotId = snapshotId;
    }

    /**
     * Converts this PlaylistSnapshotId into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaylistSnapshotId [" + "snapshotId=" + snapshotId + "]";
    }

    /**
     * Builds a new {@link PlaylistSnapshotId.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaylistSnapshotId.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .snapshotId(getSnapshotId());
        return builder;
    }

    /**
     * Class to build instances of {@link PlaylistSnapshotId}.
     */
    public static class Builder {
        private String snapshotId;



        /**
         * Setter for snapshotId.
         * @param  snapshotId  String value for snapshotId.
         * @return Builder
         */
        public Builder snapshotId(String snapshotId) {
            this.snapshotId = snapshotId;
            return this;
        }

        /**
         * Builds a new {@link PlaylistSnapshotId} object using the set fields.
         * @return {@link PlaylistSnapshotId}
         */
        public PlaylistSnapshotId build() {
            return new PlaylistSnapshotId(snapshotId);
        }
    }
}
