/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for PlaylistsTracksRequest1 type.
 */
public class PlaylistsTracksRequest1 {
    private List<String> uris;
    private Integer rangeStart;
    private Integer insertBefore;
    private Integer rangeLength;
    private String snapshotId;

    /**
     * Default constructor.
     */
    public PlaylistsTracksRequest1() {
    }

    /**
     * Initialization constructor.
     * @param  uris  List of String value for uris.
     * @param  rangeStart  Integer value for rangeStart.
     * @param  insertBefore  Integer value for insertBefore.
     * @param  rangeLength  Integer value for rangeLength.
     * @param  snapshotId  String value for snapshotId.
     */
    public PlaylistsTracksRequest1(
            List<String> uris,
            Integer rangeStart,
            Integer insertBefore,
            Integer rangeLength,
            String snapshotId) {
        this.uris = uris;
        this.rangeStart = rangeStart;
        this.insertBefore = insertBefore;
        this.rangeLength = rangeLength;
        this.snapshotId = snapshotId;
    }

    /**
     * Getter for Uris.
     * @return Returns the List of String
     */
    @JsonGetter("uris")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getUris() {
        return uris;
    }

    /**
     * Setter for Uris.
     * @param uris Value for List of String
     */
    @JsonSetter("uris")
    public void setUris(List<String> uris) {
        this.uris = uris;
    }

    /**
     * Getter for RangeStart.
     * The position of the first item to be reordered.
     * @return Returns the Integer
     */
    @JsonGetter("range_start")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getRangeStart() {
        return rangeStart;
    }

    /**
     * Setter for RangeStart.
     * The position of the first item to be reordered.
     * @param rangeStart Value for Integer
     */
    @JsonSetter("range_start")
    public void setRangeStart(Integer rangeStart) {
        this.rangeStart = rangeStart;
    }

    /**
     * Getter for InsertBefore.
     * The position where the items should be inserted.&lt;br/&gt;To reorder the items to the end of the
     * playlist, simply set _insert_before_ to the position after the last
     * item.&lt;br/&gt;Examples:&lt;br/&gt;To reorder the first item to the last position in a playlist with 10
     * items, set _range_start_ to 0, and _insert_before_ to 10.&lt;br/&gt;To reorder the last item in a
     * playlist with 10 items to the start of the playlist, set _range_start_ to 9, and
     * _insert_before_ to 0.
     * @return Returns the Integer
     */
    @JsonGetter("insert_before")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getInsertBefore() {
        return insertBefore;
    }

    /**
     * Setter for InsertBefore.
     * The position where the items should be inserted.&lt;br/&gt;To reorder the items to the end of the
     * playlist, simply set _insert_before_ to the position after the last
     * item.&lt;br/&gt;Examples:&lt;br/&gt;To reorder the first item to the last position in a playlist with 10
     * items, set _range_start_ to 0, and _insert_before_ to 10.&lt;br/&gt;To reorder the last item in a
     * playlist with 10 items to the start of the playlist, set _range_start_ to 9, and
     * _insert_before_ to 0.
     * @param insertBefore Value for Integer
     */
    @JsonSetter("insert_before")
    public void setInsertBefore(Integer insertBefore) {
        this.insertBefore = insertBefore;
    }

    /**
     * Getter for RangeLength.
     * The amount of items to be reordered. Defaults to 1 if not set.&lt;br/&gt;The range of items to be
     * reordered begins from the _range_start_ position, and includes the _range_length_ subsequent
     * items.&lt;br/&gt;Example:&lt;br/&gt;To move the items at index 9-10 to the start of the playlist,
     * _range_start_ is set to 9, and _range_length_ is set to 2.
     * @return Returns the Integer
     */
    @JsonGetter("range_length")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getRangeLength() {
        return rangeLength;
    }

    /**
     * Setter for RangeLength.
     * The amount of items to be reordered. Defaults to 1 if not set.&lt;br/&gt;The range of items to be
     * reordered begins from the _range_start_ position, and includes the _range_length_ subsequent
     * items.&lt;br/&gt;Example:&lt;br/&gt;To move the items at index 9-10 to the start of the playlist,
     * _range_start_ is set to 9, and _range_length_ is set to 2.
     * @param rangeLength Value for Integer
     */
    @JsonSetter("range_length")
    public void setRangeLength(Integer rangeLength) {
        this.rangeLength = rangeLength;
    }

    /**
     * Getter for SnapshotId.
     * The playlist's snapshot ID against which you want to make the changes.
     * @return Returns the String
     */
    @JsonGetter("snapshot_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSnapshotId() {
        return snapshotId;
    }

    /**
     * Setter for SnapshotId.
     * The playlist's snapshot ID against which you want to make the changes.
     * @param snapshotId Value for String
     */
    @JsonSetter("snapshot_id")
    public void setSnapshotId(String snapshotId) {
        this.snapshotId = snapshotId;
    }

    /**
     * Converts this PlaylistsTracksRequest1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaylistsTracksRequest1 [" + "uris=" + uris + ", rangeStart=" + rangeStart
                + ", insertBefore=" + insertBefore + ", rangeLength=" + rangeLength
                + ", snapshotId=" + snapshotId + "]";
    }

    /**
     * Builds a new {@link PlaylistsTracksRequest1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaylistsTracksRequest1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .uris(getUris())
                .rangeStart(getRangeStart())
                .insertBefore(getInsertBefore())
                .rangeLength(getRangeLength())
                .snapshotId(getSnapshotId());
        return builder;
    }

    /**
     * Class to build instances of {@link PlaylistsTracksRequest1}.
     */
    public static class Builder {
        private List<String> uris;
        private Integer rangeStart;
        private Integer insertBefore;
        private Integer rangeLength;
        private String snapshotId;



        /**
         * Setter for uris.
         * @param  uris  List of String value for uris.
         * @return Builder
         */
        public Builder uris(List<String> uris) {
            this.uris = uris;
            return this;
        }

        /**
         * Setter for rangeStart.
         * @param  rangeStart  Integer value for rangeStart.
         * @return Builder
         */
        public Builder rangeStart(Integer rangeStart) {
            this.rangeStart = rangeStart;
            return this;
        }

        /**
         * Setter for insertBefore.
         * @param  insertBefore  Integer value for insertBefore.
         * @return Builder
         */
        public Builder insertBefore(Integer insertBefore) {
            this.insertBefore = insertBefore;
            return this;
        }

        /**
         * Setter for rangeLength.
         * @param  rangeLength  Integer value for rangeLength.
         * @return Builder
         */
        public Builder rangeLength(Integer rangeLength) {
            this.rangeLength = rangeLength;
            return this;
        }

        /**
         * Setter for snapshotId.
         * @param  snapshotId  String value for snapshotId.
         * @return Builder
         */
        public Builder snapshotId(String snapshotId) {
            this.snapshotId = snapshotId;
            return this;
        }

        /**
         * Builds a new {@link PlaylistsTracksRequest1} object using the set fields.
         * @return {@link PlaylistsTracksRequest1}
         */
        public PlaylistsTracksRequest1 build() {
            return new PlaylistsTracksRequest1(uris, rangeStart, insertBefore, rangeLength,
                    snapshotId);
        }
    }
}
