/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ResumePointObject type.
 */
public class ResumePointObject {
    private Boolean fullyPlayed;
    private Integer resumePositionMs;

    /**
     * Default constructor.
     */
    public ResumePointObject() {
    }

    /**
     * Initialization constructor.
     * @param  fullyPlayed  Boolean value for fullyPlayed.
     * @param  resumePositionMs  Integer value for resumePositionMs.
     */
    public ResumePointObject(
            Boolean fullyPlayed,
            Integer resumePositionMs) {
        this.fullyPlayed = fullyPlayed;
        this.resumePositionMs = resumePositionMs;
    }

    /**
     * Getter for FullyPlayed.
     * Whether or not the episode has been fully played by the user.
     * @return Returns the Boolean
     */
    @JsonGetter("fully_played")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getFullyPlayed() {
        return fullyPlayed;
    }

    /**
     * Setter for FullyPlayed.
     * Whether or not the episode has been fully played by the user.
     * @param fullyPlayed Value for Boolean
     */
    @JsonSetter("fully_played")
    public void setFullyPlayed(Boolean fullyPlayed) {
        this.fullyPlayed = fullyPlayed;
    }

    /**
     * Getter for ResumePositionMs.
     * The user's most recent position in the episode in milliseconds.
     * @return Returns the Integer
     */
    @JsonGetter("resume_position_ms")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getResumePositionMs() {
        return resumePositionMs;
    }

    /**
     * Setter for ResumePositionMs.
     * The user's most recent position in the episode in milliseconds.
     * @param resumePositionMs Value for Integer
     */
    @JsonSetter("resume_position_ms")
    public void setResumePositionMs(Integer resumePositionMs) {
        this.resumePositionMs = resumePositionMs;
    }

    /**
     * Converts this ResumePointObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResumePointObject [" + "fullyPlayed=" + fullyPlayed + ", resumePositionMs="
                + resumePositionMs + "]";
    }

    /**
     * Builds a new {@link ResumePointObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResumePointObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fullyPlayed(getFullyPlayed())
                .resumePositionMs(getResumePositionMs());
        return builder;
    }

    /**
     * Class to build instances of {@link ResumePointObject}.
     */
    public static class Builder {
        private Boolean fullyPlayed;
        private Integer resumePositionMs;



        /**
         * Setter for fullyPlayed.
         * @param  fullyPlayed  Boolean value for fullyPlayed.
         * @return Builder
         */
        public Builder fullyPlayed(Boolean fullyPlayed) {
            this.fullyPlayed = fullyPlayed;
            return this;
        }

        /**
         * Setter for resumePositionMs.
         * @param  resumePositionMs  Integer value for resumePositionMs.
         * @return Builder
         */
        public Builder resumePositionMs(Integer resumePositionMs) {
            this.resumePositionMs = resumePositionMs;
            return this;
        }

        /**
         * Builds a new {@link ResumePointObject} object using the set fields.
         * @return {@link ResumePointObject}
         */
        public ResumePointObject build() {
            return new ResumePointObject(fullyPlayed, resumePositionMs);
        }
    }
}
