/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.spotify.api.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for SavedAlbumObject type.
 */
public class SavedAlbumObject {
    private LocalDateTime addedAt;
    private AlbumObject album;

    /**
     * Default constructor.
     */
    public SavedAlbumObject() {
    }

    /**
     * Initialization constructor.
     * @param  addedAt  LocalDateTime value for addedAt.
     * @param  album  AlbumObject value for album.
     */
    public SavedAlbumObject(
            LocalDateTime addedAt,
            AlbumObject album) {
        this.addedAt = addedAt;
        this.album = album;
    }

    /**
     * Getter for AddedAt.
     * The date and time the album was saved Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is
     * imprecise (for example, the date/time of an album release), an additional field indicates the
     * precision; see for example, release_date in an album object.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("added_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getAddedAt() {
        return addedAt;
    }

    /**
     * Setter for AddedAt.
     * The date and time the album was saved Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is
     * imprecise (for example, the date/time of an album release), an additional field indicates the
     * precision; see for example, release_date in an album object.
     * @param addedAt Value for LocalDateTime
     */
    @JsonSetter("added_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setAddedAt(LocalDateTime addedAt) {
        this.addedAt = addedAt;
    }

    /**
     * Getter for Album.
     * Information about the album.
     * @return Returns the AlbumObject
     */
    @JsonGetter("album")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AlbumObject getAlbum() {
        return album;
    }

    /**
     * Setter for Album.
     * Information about the album.
     * @param album Value for AlbumObject
     */
    @JsonSetter("album")
    public void setAlbum(AlbumObject album) {
        this.album = album;
    }

    /**
     * Converts this SavedAlbumObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SavedAlbumObject [" + "addedAt=" + addedAt + ", album=" + album + "]";
    }

    /**
     * Builds a new {@link SavedAlbumObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SavedAlbumObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addedAt(getAddedAt())
                .album(getAlbum());
        return builder;
    }

    /**
     * Class to build instances of {@link SavedAlbumObject}.
     */
    public static class Builder {
        private LocalDateTime addedAt;
        private AlbumObject album;



        /**
         * Setter for addedAt.
         * @param  addedAt  LocalDateTime value for addedAt.
         * @return Builder
         */
        public Builder addedAt(LocalDateTime addedAt) {
            this.addedAt = addedAt;
            return this;
        }

        /**
         * Setter for album.
         * @param  album  AlbumObject value for album.
         * @return Builder
         */
        public Builder album(AlbumObject album) {
            this.album = album;
            return this;
        }

        /**
         * Builds a new {@link SavedAlbumObject} object using the set fields.
         * @return {@link SavedAlbumObject}
         */
        public SavedAlbumObject build() {
            return new SavedAlbumObject(addedAt, album);
        }
    }
}
