/*
 * SpotifyWebAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.spotify.api.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for SavedShowObject type.
 */
public class SavedShowObject {
    private LocalDateTime addedAt;
    private ShowBase show;

    /**
     * Default constructor.
     */
    public SavedShowObject() {
    }

    /**
     * Initialization constructor.
     * @param  addedAt  LocalDateTime value for addedAt.
     * @param  show  ShowBase value for show.
     */
    public SavedShowObject(
            LocalDateTime addedAt,
            ShowBase show) {
        this.addedAt = addedAt;
        this.show = show;
    }

    /**
     * Getter for AddedAt.
     * The date and time the show was saved. Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is
     * imprecise (for example, the date/time of an album release), an additional field indicates the
     * precision; see for example, release_date in an album object.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("added_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getAddedAt() {
        return addedAt;
    }

    /**
     * Setter for AddedAt.
     * The date and time the show was saved. Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is
     * imprecise (for example, the date/time of an album release), an additional field indicates the
     * precision; see for example, release_date in an album object.
     * @param addedAt Value for LocalDateTime
     */
    @JsonSetter("added_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setAddedAt(LocalDateTime addedAt) {
        this.addedAt = addedAt;
    }

    /**
     * Getter for Show.
     * Information about the show.
     * @return Returns the ShowBase
     */
    @JsonGetter("show")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShowBase getShow() {
        return show;
    }

    /**
     * Setter for Show.
     * Information about the show.
     * @param show Value for ShowBase
     */
    @JsonSetter("show")
    public void setShow(ShowBase show) {
        this.show = show;
    }

    /**
     * Converts this SavedShowObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SavedShowObject [" + "addedAt=" + addedAt + ", show=" + show + "]";
    }

    /**
     * Builds a new {@link SavedShowObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SavedShowObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addedAt(getAddedAt())
                .show(getShow());
        return builder;
    }

    /**
     * Class to build instances of {@link SavedShowObject}.
     */
    public static class Builder {
        private LocalDateTime addedAt;
        private ShowBase show;



        /**
         * Setter for addedAt.
         * @param  addedAt  LocalDateTime value for addedAt.
         * @return Builder
         */
        public Builder addedAt(LocalDateTime addedAt) {
            this.addedAt = addedAt;
            return this;
        }

        /**
         * Setter for show.
         * @param  show  ShowBase value for show.
         * @return Builder
         */
        public Builder show(ShowBase show) {
            this.show = show;
            return this;
        }

        /**
         * Builds a new {@link SavedShowObject} object using the set fields.
         * @return {@link SavedShowObject}
         */
        public SavedShowObject build() {
            return new SavedShowObject(addedAt, show);
        }
    }
}
